<div align="right">
<table style="width:50%">
  <tr>
    <th>Author</th>
    <th>Version</th> 
    <th>Date</th> 
    <th>Lang.</th>
  </tr>
  <tr>
    <td>dataFLOYD</td>
    <td>v1.00</td> 
    <td>25 Aug 2018</td>
    <td>EN </td>
  </tr>
</table>
</div>

# Pyhton "numpy" library

The "numpy" library allows us to perform numeric and matrix operations efficiently in Python. If you have already used Matlab, we suggest you take a look at the tutorial on the link below. <br>
https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html <br>
If you are ready to dive into this library, let's go!

<div class="alert alert-info">
<b> ARRAYS </b> 
</div> <br>

numpy arrays are very much like Pyhton lists. Basic properties of numpy arrays: 
* All elements must be the same type
* Indexed by positive integer tuples
* We can create numpy arrays by using lists
* Elements can be accessed by using squared brackets

In [1]:
# importing the library
# the common alias for numpy is np 
import numpy as np

# create a simple np.array 
a_numpy_array = np.array([3,5,2,1])

# print it
print(a_numpy_array)

# see its type
print(type(a_numpy_array))

# look at the first element
print(a_numpy_array[0])

# change an element
a_numpy_array[1]=42

print(a_numpy_array)

[3 5 2 1]
<class 'numpy.ndarray'>
3
[ 3 42  2  1]


It is possible to change the data type of a np.array

In [2]:
a = np.array([1,2],dtype=np.int16)
b = np.array([1,2],dtype=np.float64)
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1 2]
int16
[1. 2.]
float64


In [3]:
# Creating a 2D array
# We need to pass a list comprising of two lists in order to achieve this
# The array is created row by row
b_numpy_array = np.array([[2,3,4],[4,5,6]])

# print it
print(b_numpy_array)

# In order to see its dimensions
print("\nDimensions of the matrix")
print(b_numpy_array.shape)

# Double indexing is used to access the elements
print(b_numpy_array[0,1]) # First row second column

[[2 3 4]
 [4 5 6]]

Dimensions of the matrix
(2, 3)
3


The rows of the matrix should be equal in length, otherwise we may not be able to create the desired array

In [4]:
# Let's see what happens if one row is longer than the other
c_numpy_array = np.array([[2,3,4],[4,5,6,7]])

print(c_numpy_array)

[list([2, 3, 4]) list([4, 5, 6, 7])]


** Array creation functions **

The most commonly used array creation functions are examplified below.

In [5]:
# Create a zero matrix
print("\nZero matrix")
print(np.zeros((3,2)))

# Create a ones matrix
print("\nOnes matrix")
print(np.ones((2,3)))

# Create a constant matrix
print("\nConstant matrix")
print(np.full((4,3),42))

# Identity matrix
# Note: Since this matrix is symmetrical it tales only one parameter
print("\nIdentity matrix")
print(np.eye(2))

# Random matrix
print("\nRandom matrix")
print(np.random.random((3,3)))


Zero matrix
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Ones matrix
[[1. 1. 1.]
 [1. 1. 1.]]

Constant matrix
[[42 42 42]
 [42 42 42]
 [42 42 42]
 [42 42 42]]

Identity matrix
[[1. 0.]
 [0. 1.]]

Random matrix
[[0.69621562 0.9602145  0.87007395]
 [0.44508886 0.04513239 0.05191633]
 [0.32363953 0.10999972 0.07291693]]


**np.empty() function**

This function creates an array that is empty, but does not fill inside with ones or zeros.

In [6]:
a = np.empty((2,4))
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.18570189e-321 2.22573083e-307 7.01459308e-292]]


** Slicing ** <br>
Slicing operators are used to create sub-matrices

In [7]:
a_matrix = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# Slice rows 1 to 3 and columns 2 to the end
print(a_matrix[1:3,2:])
# All last row
print(a_matrix[2,:])
# All last column
print(a_matrix[:,3])

[[ 7  8]
 [11 12]]
[ 9 10 11 12]
[ 4  8 12]


In [9]:
# print the (0,0) and (1,2) elements of the matrix
print(a_matrix[[0,1],[0,2]])

[1 7]


** np.arange() function **

This function returns evenly spaced values within a given interval. . !! Stop value is not included in the return array !!

In [10]:
# Create an array from 1 to 10
print(np.arange(1,10))
# Change the space of the elements as 2
print(np.arange(1,10,2))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


**np.linspace() function**

This function is like np.arange function. The difference between two is that np.linspace return evenly spaced numbers over a specified interval.

In [11]:
a = np.linspace(1,10,20)
print(a)
print(a.shape)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
(20,)


** Boolean indexing **

Allows us to extract/find array elements that meet a set of conditions

In [12]:
a = np.array([[1,2,5,6], [8,9,7,8], [9,10,2,42]])
print("Example matrix")
print(a)
print("\nBoolean index for numbers bigger than 5")
print([a>5])
print("\nElements bigger than 5")
print(a[a>5])
print("\nAssign 0 to elements bigger than 5")
a[a>5] = 0
print(a)

Example matrix
[[ 1  2  5  6]
 [ 8  9  7  8]
 [ 9 10  2 42]]

Boolean index for numbers bigger than 5
[array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])]

Elements bigger than 5
[ 6  8  9  7  8  9 10 42]

Assign 0 to elements bigger than 5
[[1 2 5 0]
 [0 0 0 0]
 [0 0 2 0]]


<div class="alert alert-info">
<b> MATHEMATICAL ARRAY OPERATIONS </b> 
</div>

** Elemenwise operations ** 

In [13]:
A = np.array([[1,2],[3,4]])
print("\nMatrix A")
print(A)
B = np.array([[5,6],[7,8]])
print("\nMatrix B")
print(B)

print("\nA+B")
print(A+B)
print("\nAdd constant value to matrix A")
print(A+100)
print("\nA-B")
print(A-B)
print("\nA*B")
print(A*B)
print("\nA/B")
print(A/B)
print("\nSquareroot of i.e. A sqrt(A)")
print(np.sqrt(A))
print("\nPower of A i.e. A**2")
print(A**2)


Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]

A+B
[[ 6  8]
 [10 12]]

Add constant value to matrix A
[[101 102]
 [103 104]]

A-B
[[-4 -4]
 [-4 -4]]

A*B
[[ 5 12]
 [21 32]]

A/B
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Squareroot of i.e. A sqrt(A)
[[1.         1.41421356]
 [1.73205081 2.        ]]

Power of A i.e. A**2
[[ 1  4]
 [ 9 16]]


**Matrix Operations**

In [14]:
print("Dot product A.dot(B) ")
print(A.dot(B))
print("or np.dot(A,B)")
print(np.dot(A,B))

Dot product A.dot(B) 
[[19 22]
 [43 50]]
or np.dot(A,B)
[[19 22]
 [43 50]]


In [15]:
print("Transpose A.T")
print(A.T)

Transpose A.T
[[1 3]
 [2 4]]


<div class="alert alert-info">
<b> OTHER USEFUL OPERATIONS </b> 
</div>

**Reshape**<br>
We can reshape a numpy array to another dimension or we can flatten a matrix to a vector. 

In [16]:
# Create a vector
a = np.arange(9)
print(a)

# Reshape to a 3x3 matrix
a_reshape = a.reshape((3,3))
print(a_reshape)

# Flatten the matrix back to vector form
print(a_reshape.flatten())

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


**Concatenating matrices**<br>
We can use np.concatenate() function to stack matrices vertically or horizontally. 

In [17]:
A = np.array([[1,2],[3,4]])
print("\nMatrix A")
print(A)
B = np.array([[5,6],[7,8]])
print("\nMatrix B")
print(B)

print("\nConcatenate A and B vertically")
print(np.concatenate([A,B]))
print("or use np.vstack()")
print(np.vstack([A,B]))

print("\nConcatenate A and B horizontally")
print(np.concatenate([A,B],axis=1)) # axis=1
print("or use np.hstack()")
print(np.hstack([A,B]))


Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]

Concatenate A and B vertically
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
or use np.vstack()
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate A and B horizontally
[[1 2 5 6]
 [3 4 7 8]]
or use np.hstack()
[[1 2 5 6]
 [3 4 7 8]]


**Splitting matrices**
<br> np.split() or slicing operators can be used for this purpose

In [18]:
C = np.array([[1,2,3,4],[5,6,7,8]])
print(C)
print("\n")
print("Split based on row index")
x,y = np.split(C, [1],axis=0)
print(x)
print(y)
print("\n")
print("Split based on column index")
x,y = np.split(C, [1],axis=1)
print(x)
print(y)

[[1 2 3 4]
 [5 6 7 8]]


Split based on row index
[[1 2 3 4]]
[[5 6 7 8]]


Split based on column index
[[1]
 [5]]
[[2 3 4]
 [6 7 8]]


**Add missing values and infinity to numpy arrays**<br>
* np.nan for "not-a-number"
* np.inf for infinity

In [19]:
a = np.array([[0,np.nan],[1,np.inf]])
print(a)

[[ 0. nan]
 [ 1. inf]]


**Calculate mean, median and maximum**

* np.mean(): Find mean
* np.min(): Find minimum
* np.max(): Find maximum

In [20]:
a = np.array([[1,2,5,6], [8,9,7,8], [9,10,2,42]])
print(a)
print("mean of all elements")
print(np.mean(a))
print("mean of rows")
print(np.mean(a,axis=0))
print("mean of columns")
print(np.mean(a,axis=1))

print("minimum of all elements ")
print(np.min(a))
print("minimum of rows")
print(np.min(a,axis=0))
print("minimum of columns")
print(np.min(a,axis=1))

print("maximum of all elements ")
print(np.max(a))
print("maximum of rows")
print(np.max(a,axis=0))
print("maximum of columns")
print(np.max(a,axis=1))

[[ 1  2  5  6]
 [ 8  9  7  8]
 [ 9 10  2 42]]
mean of all elements
9.083333333333334
mean of rows
[ 6.          7.          4.66666667 18.66666667]
mean of columns
[ 3.5   8.   15.75]
minimum of all elements 
1
minimum of rows
[1 2 2 6]
minimum of columns
[1 7 2]
maximum of all elements 
42
maximum of rows
[ 9 10  7 42]
maximum of columns
[ 6  9 42]


**Finding unique values**

* np.unique(): Finds the unique values and their counts (return_counts=True parameter must be added)

In [21]:
a = np.array([1,2,2,1,3,4,5,3,6,42,1,3,42,3])
print(a)

u,c = np.unique(a,return_counts=True)
print("Unique values")
print(u)
print("Unique value counts")
print(c)

[ 1  2  2  1  3  4  5  3  6 42  1  3 42  3]
Unique values
[ 1  2  3  4  5  6 42]
Unique value counts
[3 2 4 1 1 1 2]
